export const multifocal = [
  {
Name: 'Acuvue Moist',
Company: 'J&J',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.4,
LD: 14.3,
WaterContent: '58%',
Dkt: 28,
Modulus: '',
SphMin: -9,
SphMax: 6,
Steps: '',
Add: 'Low: +0.75 to +1.25\nMid: +1.50 to +1.75\nHigh: +2.00 to +2.50',
AddDesign: '',
Notes: 'Aspheric centre, spherical periphery (ensure centration of optics over the pupil). Inside out mark'
  },
  {
Name: 'Air Optix Aqua',
Company: 'Alcon',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14.2,
WaterContent: '33%',
Dkt: 138,
Modulus: 1,
SphMin: -10,
SphMax: 6,
Steps: '',
Add: 'Low: up to +1.25\nMed: +1.50 to +2.00\nHi: +2.25 to +2.50',
AddDesign: 'Centre-N',
Notes: 'EW 6 nights'
  },
  {
Name: 'Biofinity',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14,
WaterContent: '48%',
Dkt: 142,
Modulus: 0.75,
SphMin: -10,
SphMax: 6,
Steps: '',
Add: 'Options: +1.00, +1.50, +2.00. +2.50',
AddDesign: 'Both Centre-D and Centre N',
Notes: 'EW 29 nights'
  },
  {
Name: 'Biotrue ONEday',
Company: 'B&L',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.2,
WaterContent: '78%',
Dkt: 42,
Modulus: 0.49,
SphMin: -9,
SphMax: 6,
Steps: '',
Add: 'Low: +0.75 to +1.50\nHigh: +1.75 to +2.50',
AddDesign: 'Centre-N',
Notes: 'Hypergel'
  },
  {
Name: 'Clariti 1 Day',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.1,
WaterContent: '56%',
Dkt: 86,
Modulus: 0.5,
SphMin: -6,
SphMax: 5,
Steps: '',
Add: 'Low: up to +2.25 \nHigh: +2.25 to +3.00',
AddDesign: 'Centre-N',
Notes: ''
  },
  {
Name: 'Dailies Aquacomfort Plus',
Company: 'Alcon',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.7,
LD: 14,
WaterContent: '69%',
Dkt: 26,
Modulus: '',
SphMin: -10,
SphMax: 6,
Steps: '',
Add: 'Low: up to +1.25\nMed: +1.50 to +2.00\nHigh: +2.25 to +2.50',
AddDesign: 'Centre-N',
Notes: ''
  },
  {
Name: 'Dailies Total1',
Company: 'Alcon',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.5,
LD: 14.1,
WaterContent: '33%',
Dkt: 156,
Modulus: '0.76-0.014',
SphMin: -6,
SphMax: 3,
Steps: '',
Add: 'Low: up to +1.25\nMed: +1.50 to +2.00\nHigh:+2.25 to +2.50',
AddDesign: '',
Notes: ''
  },
  {
Name: 'Proclear',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14.4,
WaterContent: '62%',
Dkt: 17,
Modulus: 0.49,
SphMin: -8,
SphMax: 6,
Steps: '0.25 until -6.50 (then 0.50)',
Add: 'Options: +1.00, +1.50, +2.00. +2.50',
AddDesign: 'Both Centre-D and Centre N',
Notes: ''
  },
  {
Name: 'Proclear 1 day',
Company: 'Coopervision',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.7,
LD: 14.2,
WaterContent: '60%',
Dkt: 28,
Modulus: 0.4,
SphMin: -10,
SphMax: 6,
Steps: '',
Add: 'Single add',
AddDesign: 'Centre-N',
Notes: ''
  },
  {
Name: 'Proclear Toric',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: '8.4 & 8.8',
LD: 14.4,
WaterContent: '62%',
Dkt: 17,
Modulus: 0.49,
SphMin: -20,
SphMax: 20,
Steps: '0.5 steps after +6.50/-6.50',
Add: 'Options: +1.00 to +4.00 (0.50D steps)',
AddDesign: 'Both Centre-D and Centre N',
Notes: 'Cyl -0.75 to -5.75 (0.50D steps) Axis 5 to 180 (5 degree steps)'
  },
  {
Name: 'Proclear XR',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14.4,
WaterContent: '62%',
Dkt: 17,
Modulus: 0.49,
SphMin: 6.25,
SphMax: 20,
Steps: '6.25, 6.50 to 20 (0.50D steps)',
Add: 'Options: +1.00 to +4.00 (0.50D steps)',
AddDesign: 'Both Centre-D and Centre N',
Notes: 'High Plus Options'
  },
  {
Name: 'Proclear XR',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14.4,
WaterContent: '62%',
Dkt: 17,
Modulus: 0.49,
SphMin: -20,
SphMax: 8.5,
Steps: 0.5,
Add: 'Options: +1.00 to +4.00 (0.50D steps)',
AddDesign: 'Both Centre-D and Centre N',
Notes: 'High Minus Options'
  },
  {
Name: 'Proclear XR',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14.4,
WaterContent: '62%',
Dkt: 17,
Modulus: 0.49,
SphMin: -8,
SphMax: 6,
Steps: '0.25 until -6.50 (then 0.50)',
Add: 'Higher cyl Options: +3.00, +3.50. +4.00',
AddDesign: 'Both Centre-D and Centre N',
Notes: 'High Cyl Options'
  },
  {
Name: 'PureVision 2 HD',
Company: 'B&L',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14,
WaterContent: '36%',
Dkt: 130,
Modulus: 1.1,
SphMin: -10,
SphMax: 6,
Steps: 0.25,
Add: 'Low: +0.75 to +1.50\nHigh: +1.75 to +2.50',
AddDesign: 'Centre-N',
Notes: ''
  },
  {
Name: 'SofLens',
Company: 'B&L',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: '8.5 & 8.8',
LD: 14.5,
WaterContent: '38.60%',
Dkt: 8.4,
Modulus: '',
SphMin: -10,
SphMax: 6,
Steps: '',
Add: 'Low: +0.75 to +1.50 \nHigh: +1.75 to +2.50',
AddDesign: 'Centre-N',
Notes: ''
  },
  {
Name: 'Ultra for Presbyopia',
Company: 'B&L',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.5,
LD: 14.2,
WaterContent: '46%',
Dkt: 163,
Modulus: 0.7,
SphMin: -7,
SphMax: 2,
Steps: '',
Add: 'Low: +0.75 to +1.50\nHigh: +1.75 to +2.50',
AddDesign: 'Centre-N',
Notes: ''
  }
];
