export const spherical = [
  {
Name: 'Dailies Aqua Comfort Plus',
Company: 'Alcon',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.7,
LD: 14,
WaterContent: '69%',
Dkt: 26,
Modulus: '',
SphMin: -15,
SphMax: 8,
Steps: '0.25 until +6/-6',
Notes: '',
Marketing: '',
  },
  {
Name: 'Dailies Total1',
Company: 'Alcon',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.5,
LD: 14.1,
WaterContent: '33% to 80%',
Dkt: 156,
Modulus: '0.7-0.025',
SphMin: -12,
SphMax: 6,
Steps: '0.25 until +6/-6',
Notes: '',
Marketing: '',
  },
  {
Name: 'Air Optix Aqua',
Company: 'Alcon',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14.2,
WaterContent: '33%',
Dkt: 138,
Modulus: 1,
SphMin: -12,
SphMax: 8,
Steps: '0.25 until +6/-6',
Notes: 'EW 6 nights',
Marketing: '',
  },
  {
Name: 'Air Optix Night & Day Aqua',
Company: 'Alcon',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: '8.4 / 8.6',
LD: 13.8,
WaterContent: '24%',
Dkt: 175,
Modulus: 1.5,
SphMin: -10,
SphMax: 6,
Steps: '0.25 until +6/-8',
Notes: 'EW 30 nights',
Marketing: '',
  },
  {
Name: 'PureVision 2 HD',
Company: 'B&L',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14,
WaterContent: '36%',
Dkt: 130,
Modulus: '',
SphMin: -12,
SphMax: 6,
Steps: '0.25 until +6/-6',
Notes: 'EW 30 days',
Marketing: 'replaced Purevision \'thinner\' alternative',
  },
  {
Name: 'SofLens',
Company: 'B&L',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.2,
WaterContent: '60%',
Dkt: 22,
Modulus: '',
SphMin: -9,
SphMax: 6.5,
Steps: '0.25 until +6.50/-6.50',
Notes: '',
Marketing: '',
  },
  {
Name: 'Biotrue ONEday',
Company: 'B&L',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.2,
WaterContent: '78%',
Dkt: 42,
Modulus: 0.49,
SphMin: -9,
SphMax: 6,
Steps: '0.25 until +6/-6.50',
Notes: '',
Marketing: 'Hypergel, moisture retained for longer (16 h)',
  },
  {
Name: 'Ultra',
Company: 'B&L',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.5,
LD: 14.2,
WaterContent: '46%',
Dkt: 163,
Modulus: 0.7,
SphMin: -9,
SphMax: 6.5,
Steps: '0.25 until +6.50/-6.50',
Notes: '',
Marketing: 'Thin edge enables smooth gentle transition between lens/lid. Better for low light vision, less spherical aberrations (movies/driving)',
  },
  {
Name: 'Biofinity XR',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14,
WaterContent: '48%',
Dkt: 160,
Modulus: 0.75,
SphMin: -20,
SphMax: 15,
Steps: 0.5,
Notes: '',
Marketing: '',
  },
  {
Name: 'Proclear',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14.2,
WaterContent: '62%',
Dkt: 27,
Modulus: 0.4,
SphMin: -20,
SphMax: 20,
Steps: '0.25 until +6/-6',
Notes: '',
Marketing: '',
  },
  {
Name: 'Proclear 1 Day',
Company: 'Coopervision',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.7,
LD: 14.2,
WaterContent: '60%',
Dkt: 28,
Modulus: 0.4,
SphMin: -12,
SphMax: 8,
Steps: '0.25 until -6/5',
Notes: '',
Marketing: '',
  },
  {
Name: 'Avaira',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Fortnightly',
BaseCurve: '8.5 (-) / 8.4 (+)',
LD: 14.2,
WaterContent: '46%',
Dkt: 125,
Modulus: 0.5,
SphMin: -12,
SphMax: 8,
Steps: '0.25 until +6/-6',
Notes: '',
Marketing: '',
  },
  {
Name: 'Biofinity',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14,
WaterContent: '48%',
Dkt: 160,
Modulus: 0.75,
SphMin: -12,
SphMax: 8,
Steps: '0.25 until +6/-6',
Notes: 'EW 29 nights',
Marketing: '',
  },
  {
Name: 'Biofinity ENERGYS',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: 14,
WaterContent: '48%',
Dkt: 160,
Modulus: 0.75,
SphMin: -12,
SphMax: 8,
Steps: '0.25 until +6/-6',
Notes: '',
Marketing: 'Digital zone optics with multiple front surface aspheric curves to ease accommodative burden of a digital lifestyle',
  },
  {
Name: 'Biomedics 1 day Extra',
Company: 'Coopervision',
Material: 'H',
Replacement: 'DD',
BaseCurve: '8.6 (-) / 8.8 (+)',
LD: 14.2,
WaterContent: '55%',
Dkt: 27,
Modulus: '',
SphMin: -10,
SphMax: 6,
Steps: '0.25 till -6/+5',
Notes: '2 BC (different for +/-)',
Marketing: '',
  },
  {
Name: 'Clariti 1 Day',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.1,
WaterContent: '56%',
Dkt: 86,
Modulus: 0.5,
SphMin: -10,
SphMax: 8,
Steps: '0.25 until +6/-6',
Notes: '',
Marketing: '',
  },
  {
Name: 'MyDay',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.4,
LD: 14.2,
WaterContent: '54%',
Dkt: 100,
Modulus: 0.4,
SphMin: -10,
SphMax: 6,
Steps: '0.25 until +5.50/-6.50',
Notes: '',
Marketing: '',
  },
  {
Name: 'cAir',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Fortnightly',
BaseCurve: 8.4,
LD: 14.1,
WaterContent: '55%',
Dkt: 90,
Modulus: 0.5,
SphMin: -10,
SphMax: 8,
Steps: '0.25 until +6/-6',
Notes: '',
Marketing: '',
  },
  {
Name: 'Acuvue Moist',
Company: 'J&J',
Material: 'H',
Replacement: 'DD',
BaseCurve: '8.5 / 9',
LD: 14.2,
WaterContent: '58%',
Dkt: 26,
Modulus: 0.31,
SphMin: -12,
SphMax: 6,
Steps: '0.25 until +6/-6',
Notes: '2 BC',
Marketing: '',
  },
  {
Name: 'Acuvue Oasys 1 Day',
Company: 'J&J',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: '8.5 / 9',
LD: 14.3,
WaterContent: '38%',
Dkt: 121,
Modulus: 0.72,
SphMin: -12,
SphMax: 8,
Steps: '0.25 until +6.50/-6.50',
Notes: '2 BC',
Marketing: '',
  },
  {
Name: 'Acuvue Trueye',
Company: 'J&J',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: '8.5 / 9',
LD: 14.2,
WaterContent: '46%',
Dkt: 118,
Modulus: '0.66-0.71',
SphMin: -12,
SphMax: 6,
Steps: '0.25 until +6/-6',
Notes: '2 BC',
Marketing: '',
  },
  {
Name: 'Oasys',
Company: 'J&J',
Material: 'SiH',
Replacement: 'Fortnightly',
BaseCurve: '8.4 / 8.8',
LD: 14,
WaterContent: '38%',
Dkt: 147,
Modulus: 0.72,
SphMin: -12,
SphMax: 10,
Steps: '0.25 until +6/-6',
Notes: '2 BC',
Marketing: '',
  },
  {
Name: 'Acuvue VITA',
Company: 'J&J',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: '8.4 / 8.8',
LD: 14,
WaterContent: '41%',
Dkt: 147,
Modulus: '',
SphMin: -12,
SphMax: 8,
Steps: '0.25 until +6/-6',
Notes: '2 BC',
Marketing: 'UV blocker, visibility/inside out tint. Hydramax allow uniform lipid distribution and density = good lens hydration reduced evaporation',
  },
  {
Name: 'Miru 1 Month',
Company: 'Menicon',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: '8.3 / 8.6',
LD: 14,
WaterContent: '40%',
Dkt: 161,
Modulus: '',
SphMin: -13,
SphMax: 6,
Steps: '0.25 until +6/-6',
Notes: '',
Marketing: 'Spherical optics; comfortable thin tapered edge, treated on surface with menisilk & nanogloss tech (greater resistance to lipid deposition  less discomfort, inflammation) Better corneal oxygenation across entire lens, low bacterial adhesion',
  },
  {
Name: 'Miru 1 Day',
Company: 'Menicon',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.2,
WaterContent: '57%',
Dkt: 25,
Modulus: '',
SphMin: -10,
SphMax: -0.5,
Steps: '',
Notes: 'Flat Pack',
Marketing: '',
  }
];
