export const tinted = [
  {
Name: 'FreshLook One-Day',
Company: 'Alcon',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.6,
LD: '',
WaterContent: '69%',
Dkt: 26,
Modulus: '',
SphMin: -8,
SphMax: -0.5,
Steps: '',
Tints: 'Blue\nGreen\nPure Hazel\nGrey',
Notes: '',
Marketing: ''
  },
  {
Name: 'FreshLook Colors',
Company: 'Alcon',
Material: 'H',
Replacement: 'Fortnightly',
BaseCurve: '',
LD: '',
WaterContent: '55%',
Dkt: 20,
Modulus: '',
SphMin: -6,
SphMax: 6,
Steps: '',
Tints: 'Blue\nGreen\nHazel\nViolet',
Notes: '',
Marketing: ''
  },
  {
Name: 'Freshlook Colorblends',
Company: 'Alcon',
Material: 'H',
Replacement: 'Fortnightly',
BaseCurve: '',
LD: '',
WaterContent: '55%',
Dkt: 20,
Modulus: '',
SphMin: -8,
SphMax: 6,
Steps: '',
Tints: 'Amethyst\nBlue\nBrilliant Blue\nBrown\nGemstone Green\nGray, Green\nHoney\nPure Hazel\nSterling Gray\nTrue Sapphire\nTurquoise',
Notes: '',
Marketing: ''
  },
  {
Name: 'FreshLook Dimension',
Company: 'Alcon',
Material: 'H',
Replacement: 'Fortnightly',
BaseCurve: '',
LD: '',
WaterContent: '55%',
Dkt: 20,
Modulus: '',
SphMin: -8,
SphMax: 6,
Steps: '',
Tints: '',
Notes: '',
Marketing: ''
  },
  {
Name: 'AirOptix Colors',
Company: 'Alcon',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.6,
LD: '',
WaterContent: '33%',
Dkt: '138',
Modulus: '',
SphMin: -8,
SphMax: 6,
Steps: '',
Tints: 'Subtle:\nBlue\nGreen\nBrown\nPure Hazel\nGrey\nVibrant: \nBrilliant Blue\nGemstone Green\nSterling Gray\nHoney',
Notes: '',
Marketing: ''
  },
  {
Name: 'Acuvue Define',
Company: 'J&J',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.5,
LD: 14.2,
WaterContent: '58%',
Dkt: 26,
Modulus: '',
SphMin: -9,
SphMax: 0,
Steps: '',
Tints: 'Vivid D 12.8mm\nAccent D 12.5mm\nNatural Shine D 12.7mm\nNatural sparkle\nNatural shimmer',
Notes: '',
Marketing: ''
  }
];
