// tslint:disable-next-line: no-unused-expression
export const toric = [
  {
Name: 'Dailies AquaComfort PLus',
Company: 'Alcon',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.8,
LD: 14.4,
WaterContent: '69%',
Dkt: 26,
Modulus: 0.9,
SphMin: -8,
SphMax: 4,
SphSteps: '',
CylMin: -0.75,
CylMax: -1.75,
CylSteps: '',
Axis: '',
Markings: '',
Notes: '',
Marketing: '',
Stabilisation: 'dual thin zone, double slab off design',
  },
  {
Name: 'Air Optix for Astig',
Company: 'Alcon',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14,
WaterContent: '33%',
Dkt: 108,
Modulus: 1,
SphMin: -10,
SphMax: 6,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: '',
Axis: '',
Markings: '3, 6 9 o\'clock',
Notes: 'EW 6 nights',
Marketing: '',
Stabilisation: 'prism ballast',
  },
  {
Name: 'Biotrue',
Company: 'B&L',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.4,
LD: 14.5,
WaterContent: '78%',
Dkt: 42,
Modulus: 0.5,
SphMin: -9,
SphMax: 4,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: '',
Axis: '',
Markings: '',
Notes: '',
Marketing: 'Hypergel, prism free optic zone',
Stabilisation: 'peri ballast',
  },
  {
Name: 'SofLens Toric',
Company: 'B&L',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.2,
WaterContent: '59%',
Dkt: 22,
Modulus: '',
SphMin: -9,
SphMax: 0,
SphSteps: '',
CylMin: -0.75,
CylMax: -1.75,
CylSteps: '',
Axis: '',
Markings: '',
Notes: '',
Marketing: '',
Stabilisation: 'prism ballast',
  },
  {
Name: 'SofLens 66 Toric',
Company: 'B&L',
Material: 'H',
Replacement: 'Fortnightly',
BaseCurve: 8.5,
LD: 14.5,
WaterContent: '66%',
Dkt: 16,
Modulus: '',
SphMin: -9,
SphMax: 6,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.75,
CylSteps: '',
Axis: '',
Markings: '5, 6, 7 o\'clock',
Notes: '',
Marketing: '',
Stabilisation: '',
  },
  {
Name: 'PureVision Toric',
Company: 'B&L',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14,
WaterContent: '36%',
Dkt: 91,
Modulus: 1.1,
SphMin: -9,
SphMax: 6,
SphSteps: '',
CylMin: -0.75,
CylMax: -1.75,
CylSteps: '',
Axis: '',
Markings: '5,6,7 o\'clock',
Notes: 'EW 30 days',
Marketing: '',
Stabilisation: 'prism ballast',
  },
  {
Name: 'PureVision 2',
Company: 'B&L',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.9,
LD: 14.5,
WaterContent: '36%',
Dkt: 91,
Modulus: 1.1,
SphMin: -9,
SphMax: 6,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: '',
Axis: '',
Markings: '5,6,7 o\'clock',
Notes: 'EW 30 days',
Marketing: '',
Stabilisation: 'hybrid ballast',
  },
  {
Name: 'Clariti 1 Day',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.3,
WaterContent: '56%',
Dkt: 57,
Modulus: 0.5,
SphMin: -9,
SphMax: 4,
SphSteps: '0.25 until +4/-6',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: 0.5,
Axis: '',
Markings: '6 o\'clock',
Notes: '-2.25 only for minus',
Marketing: 'Aspheric',
Stabilisation: '',
  },
  {
Name: 'Myday',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.5,
WaterContent: '54%',
Dkt: 80,
Modulus: 0.4,
SphMin: -10,
SphMax: 6,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: 0.5,
Axis: '',
Markings: '6 o\'clock',
Notes: 'optimised toric lens geometry, uniform lens thickness, large optic zone',
Marketing: '',
Stabilisation: '',
  },
  {
Name: 'Biomedics 1 day extra',
Company: 'Coopervision',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.7,
LD: 14.5,
WaterContent: '55%',
Dkt: 17,
Modulus: '',
SphMin: 0,
SphMax: 10,
SphSteps: '',
CylMin: -0.75,
CylMax: -1.75,
CylSteps: '',
Axis: '',
Markings: '',
Notes: '',
Marketing: '',
Stabilisation: 'back surface toric with wide ballast band',
  },
  {
Name: 'Avaira Toric',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Fortnightly',
BaseCurve: 8.5,
LD: 14.5,
WaterContent: '46%',
Dkt: 91,
Modulus: 0.5,
SphMin: -10,
SphMax: 6,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: '',
Axis: '',
Markings: '6 o\'clock',
Notes: '',
Marketing: '',
Stabilisation: 'back surface toric with wide ballast band',
  },
  {
Name: 'cAir Toric',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Fortnightly',
BaseCurve: 8.5,
LD: 14.5,
WaterContent: '55%',
Dkt: 90,
Modulus: 0.6,
SphMin: -10,
SphMax: 6,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: '',
Axis: '',
Markings: '6 o\'clock',
Notes: '',
Marketing: '',
Stabilisation: 'back surface toric with wide ballast band',
  },
  {
Name: 'Biofinity Toric',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14.5,
WaterContent: '48%',
Dkt: 116,
Modulus: 0.75,
SphMin: -10,
SphMax: 8,
SphSteps: '0.25 until +6/-6',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: 0.5,
Axis: '10 to 180 (10 steps)',
Markings: '6 o\'clock',
Notes: 'EW 29 nights',
Marketing: '',
Stabilisation: 'back surface toric with wide ballast band',
  },
  {
Name: 'Biofinity Toric XR',
Company: 'Coopervision',
Material: 'SiH',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14.5,
WaterContent: '48%',
Dkt: 116,
Modulus: '',
SphMin: -10,
SphMax: 10,
SphSteps: 0.5,
CylMin: -0.75,
CylMax: -5.75,
CylSteps: 0.5,
Axis: '5 to 180 (5 steps)',
Markings: '6 o\'clock',
Notes: 'EW 29 nights',
Marketing: '',
Stabilisation: '',
  },
  {
Name: 'Proclear',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: 8.8,
LD: 14.5,
WaterContent: '62%',
Dkt: 30.9,
Modulus: 0.4,
SphMin: -8,
SphMax: 6,
SphSteps: '0.5 after -6',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: 0.5,
Axis: '10 to 180 (10 steps)',
Markings: '6 o\'clock and 15 degrees other side',
Notes: '',
Marketing: '',
Stabilisation: '',
  },
  {
Name: 'Proclear XR',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: '8.4 & 8.8',
LD: 14.5,
WaterContent: '62%',
Dkt: 30.9,
Modulus: 0.4,
SphMin: -8,
SphMax: 6,
SphSteps: '0.25 until +6.50/-8',
CylMin: -2.75,
CylMax: -5.75,
CylSteps: 0.5,
Axis: '5 to 180 (5 steps)',
Markings: '6 o\'clock and 15 degrees other side',
Notes: 'High cyl Options',
Marketing: '',
Stabilisation: 'back surface toric with prism ballast',
  },
  {
Name: 'Proclear XR',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: '8.4 & 8.8',
LD: 14.5,
WaterContent: '62%',
Dkt: 30.9,
Modulus: 0.4,
SphMin: -10,
SphMax: -8.5,
SphSteps: 0.5,
CylMin: -0.75,
CylMax: -5.75,
CylSteps: 0.5,
Axis: '5 to 180 (5 steps)',
Markings: '6 o\'clock and 15 degrees other side',
Notes: 'High minus + cyl options',
Marketing: '',
Stabilisation: 'back surface toric with prism ballast',
  },
  {
Name: 'Proclear XR',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: '8.4 & 8.8',
LD: 14.5,
WaterContent: '62%',
Dkt: 30.9,
Modulus: 0.4,
SphMin: 6.25,
SphMax: 10,
SphSteps: '6.25 then 0.5 steps from 6.5/10',
CylMin: -0.75,
CylMax: -5.75,
CylSteps: 0.5,
Axis: '5 to 180 (5 steps)',
Markings: '6 o\'clock and 15 degrees other side',
Notes: 'High plu + cyl options',
Marketing: '',
Stabilisation: 'back surface toric with prism ballast',
  },
  {
Name: 'Frequency Xcel XR',
Company: 'Coopervision',
Material: 'H',
Replacement: 'Monthly',
BaseCurve: 8.7,
LD: 14.4,
WaterContent: '55%',
Dkt: 15.7,
Modulus: '',
SphMin: -8,
SphMax: 6,
SphSteps: '',
CylMin: -2.75,
CylMax: -3.75,
CylSteps: '',
Axis: '',
Markings: '',
Notes: '',
Marketing: '',
Stabilisation: '',
  },
  {
Name: 'Oasys',
Company: 'J&J',
Material: 'SiH',
Replacement: 'DD',
BaseCurve: 8.6,
LD: 14.5,
WaterContent: '38%',
Dkt: 129,
Modulus: 0.72,
SphMin: -9,
SphMax: 4,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.75,
CylSteps: '',
Axis: '',
Markings: '6 & 12 o\'clock',
Notes: '',
Marketing: '',
Stabilisation: 'blink stabilised design',
  },
  {
Name: 'Acuvue Moist',
Company: 'J&J',
Material: 'H',
Replacement: 'DD',
BaseCurve: 8.5,
LD: 14.5,
WaterContent: '58%',
Dkt: 26,
Modulus: 0.3,
SphMin: -6,
SphMax: 4,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: '',
Axis: '',
Markings: '',
Notes: '',
Marketing: '',
Stabilisation: 'dynamic multizone blink stabilised design',
  },
  {
Name: 'Acuvue Oasys for Astigmatism',
Company: 'J&J',
Material: 'SiH',
Replacement: 'Fortnightly',
BaseCurve: 8.6,
LD: 14.5,
WaterContent: '38%',
Dkt: 129,
Modulus: 0.72,
SphMin: -9,
SphMax: 0.25,
SphSteps: '',
CylMin: -0.75,
CylMax: -2.25,
CylSteps: '',
Axis: '',
Markings: '6 & 12 o\'clock',
Notes: '',
Marketing: '',
Stabilisation: '',
  }
];
